name: .NET CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: |
        dotnet restore src/logging.csproj
        dotnet restore logging-demo/logging-demo.csproj

    - name: Build library and demo
      run: |
        dotnet build src/logging.csproj -c Release --no-restore
        dotnet build logging-demo/logging-demo.csproj -c Debug --no-restore

    - name: Run demo (sanity check)
      run: dotnet run --project logging-demo/logging-demo.csproj

    - name: Package library
      run: dotnet pack src/logging.csproj -c Release -o ./artifacts

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ZakariaAitAli.Logging
        path: ./artifacts

    - name: Publish to GitHub Packages
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet nuget add source \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          --name github \
          "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

        dotnet nuget push ./artifacts/*.nupkg --source github
